AirDrop/Controllers/CryptosController.cs
using AirDrop.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace AirDrop.Controllers
{
    public class CryptosController : Controller
    {
        public IActionResult Index()
        {
            // return View();
            

            ViewBag.cryptoList = GetCurrencyData();
            return View();
        }

        public IActionResult bitcoin()
        {
            ViewBag.bitcoin = BitcoinData();
            return View();
        }

        public IActionResult ethereum()
        {
            ViewBag.ethereum = EthereumData();
            return View();
        }

        public IActionResult binance()
        {
            ViewBag.binance = BinanceData();
            return View();
        }

        public List<CryptoCurrencyData> GetCurrencyData()
        {
            List<CryptoCurrencyData> currency = new List<CryptoCurrencyData>();

            using (var client = new HttpClient()) {
                client.BaseAddress = new Uri("https://api.nomics.com/v1/");
                var responseTask = client.GetAsync("currencies/ticker?key=60554f1aac4ec6ecf9d934a78719834f353163ae&&interval=1d&per-page=20&page=1"
                   );
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode) {
                    Task<string> json = result.Content.ReadAsStringAsync();
                  //  dynamic currencyData = JsonConvert.DeserializeObject<List<CryptoCurrencyData>>(json.Result);
                    List<CryptoCurrencyData> currencyData = JsonConvert.DeserializeObject<List<CryptoCurrencyData>>(json.Result);
                    return currencyData;
                }
            }
            return null;
        }

        public List<CryptoCurrencyData> BitcoinData()
        {
            using (HttpClient client = new HttpClient()) {
                client.BaseAddress = new Uri("https://api.nomics.com/v1/");
                
                var responseTask = client.GetAsync("currencies/ticker?key=60554f1aac4ec6ecf9d934a78719834f353163ae&ids=BTC&interval=1d");
                responseTask.Wait(10000);

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode) {
                    Task<string> json = result.Content.ReadAsStringAsync();
                    dynamic data = JsonConvert.DeserializeObject<List<CryptoCurrencyData>>(json.Result);

                    return data;
                }
            }
            return null;
        }

        public List<CryptoCurrencyData> EthereumData()
        {
            using (HttpClient client = new HttpClient()) {
                client.BaseAddress = new Uri("https://api.nomics.com/v1/");

                var responseTask = client.GetAsync("currencies/ticker?key=60554f1aac4ec6ecf9d934a78719834f353163ae&ids=ETH&interval=1d");
                responseTask.Wait(10000);

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode) {
                    Task<string> json = result.Content.ReadAsStringAsync();
                    dynamic data = JsonConvert.DeserializeObject<List<CryptoCurrencyData>>(json.Result);

                    return data;
                }
            }
            return null;
        }

        public List<CryptoCurrencyData> BinanceData()
        {
            using (HttpClient client = new HttpClient()) {
                client.BaseAddress = new Uri("https://api.nomics.com/v1/");

                var responseTask = client.GetAsync("currencies/ticker?key=60554f1aac4ec6ecf9d934a78719834f353163ae&ids=BNB&interval=1d");
                responseTask.Wait(10000);

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode) {
                    Task<string> json = result.Content.ReadAsStringAsync();
                    dynamic data = JsonConvert.DeserializeObject<List<CryptoCurrencyData>>(json.Result);

                    return data;
                }
            }
            return null;
        }
    }
}

AirDrop/Controllers/PredictionController.cs
using AirDrop.Models;
using AirDropML.Model;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace AirDrop.Controllers
{
    public class PredictionController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {

            return View();

        }

        
        public IActionResult bitcoin()
        {
            
            

            return View();
        }

        [HttpPost]
        public IActionResult Index(ModelInput input)
        {
            List<DataPoints> dataPoints = new List<DataPoints>();

            ViewBag.Result = "";
            var prediction = ConsumeModel.Predict(input);
            ViewBag.Result = prediction;

            
            
            ViewData["Open"] = input.Open;
            ViewData["High"] = input.High;
            ViewData["Low"] = input.Low;
            dataPoints.Add(new DataPoints("Predictied Price", ViewBag.Result.Score));

            ViewBag.DataPoints = JsonConvert.SerializeObject(dataPoints);
            return View();
        }

       
    }
}

AirDrop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title class="text-black-50 ">@ViewData["Title"] - AirDrop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
  @*  <header class="header-main">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm">
            <div class="container">
                <a class="navbar-brand font-weight-normal website-name" asp-area="" asp-controller="Home" asp-action="Index" title="Go to homepage">AirDrop</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse ">
                    <ul class="flex-grow-1">
                        <li class="">
                            <a class="nav-text nav-link text-dark navbar-text-margin" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        

    </header>*@
    
   <header class="d-lg-block">

        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  box-shadow mb-3">

            <div class="container">

                <a class="navbar-brand font-weight-normal website-name" asp-area="" asp-controller="Home" asp-action="Index" title="Go to homepage">AirDrop</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class=" navbar-collapse collapse d-sm-inline-flex justify-content-between float-right">
                    <ul class="navbar-nav flex-grow-1 font-weight-normal  " style="font-size:20px">
                        <li class="nav-item">
                            <a class="nav-text nav-link text-dark navbar-text-margin" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-text nav-link text-dark navbar-text-margin" asp-area="" asp-controller="Cryptos" asp-action="Index">
                                CryptoCurrencies
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-text nav-link text-dark navbar-text-margin" asp-area="" asp-controller="Prediction" asp-action="Index">Prediction</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-text nav-link text-dark navbar-text-margin" asp-area="" asp-controller="Home" asp-action="CryptoInfo">What Is Crypto</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-text nav-link text-dark navbar-text-margin" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted ">
        <div class="container">
            &copy; 2021 - AirDrop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>